/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.DbCon;

/**
 *
 * @author user
 */
public class DeshBoard2 extends javax.swing.JFrame {

    DbCon con = new DbCon();
    PreparedStatement ps;
    String sql = "";
    ResultSet rs;

    /**
     * Creates new form DeshBoard2
     */
    public DeshBoard2() {
        initComponents();

        getAllPassengerData();
        getAllFlightsData();

        getPassenger();
        getPassengerData();
    }

    //conver to util date to sql date
    public static Date convertDateToSql(java.util.Date utilDate) {
        if (utilDate != null) {
            return new Date(utilDate.getTime());
        }
        return null;
    }

    //Get data from mysql table
    String[] tableColumns = {"p_id", "p_name", "p_nationality", "p_gender", "p_passport", "p_address", "p_phone"};

    public void getAllPassengerData() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(tableColumns);

        tblPassengers.setModel(model);

        sql = "select * from passengers_table";

        try {
            ps = con.getCon().prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("p_id");
                String name = rs.getString("p_name");
                String nationality = rs.getString("p_nationality");
                String gender = rs.getString("p_gender");
                String passport = rs.getString("p_passport");
                String address = rs.getString("p_address");
                String phone = rs.getString("p_phone");

                model.addRow(new Object[]{id, name, nationality, gender, passport, address, phone});
            }
            ps.close();
            con.getCon().close();

        } catch (SQLException ex) {
            Logger.getLogger(DeshBoard2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void reset() {
        pName.setText(null);
        pNatinality.setSelectedItem(null);
        pGender.setSelectedItem(null);
        pPassport.setText(null);
        pAddress.setText(null);
        pPhone.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCancellation = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnFlights = new javax.swing.JButton();
        btnPassengers = new javax.swing.JButton();
        btnTickets = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        maintab = new javax.swing.JTabbedPane();
        home = new javax.swing.JTabbedPane();
        jPanel21 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        flights = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        btnfDelete = new javax.swing.JButton();
        flDate = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        flSource = new javax.swing.JComboBox<>();
        flDestination = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        flCode = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        flSeats = new javax.swing.JTextField();
        btnfSave = new javax.swing.JButton();
        btnfUpdate = new javax.swing.JButton();
        btnfReset = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblFlights = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passengers = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pPassport = new javax.swing.JTextField();
        pNatinality = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        pName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pGender = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pAddress = new javax.swing.JTextField();
        pPhone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPassengers = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tickets = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        btnSaveTickt = new javax.swing.JButton();
        btnUpdateTickt = new javax.swing.JButton();
        btnResetTickt = new javax.swing.JButton();
        btnDeleteTickt = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        PassIdTickt = new javax.swing.JComboBox<>();
        nameTickt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        flightCodeTickt = new javax.swing.JComboBox<>();
        genderTicket = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        passportTickt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        amountTickt = new javax.swing.JTextField();
        nationalityTickt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTickets = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cancellation = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jPanel18 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 113, 188));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/txtLogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 70));

        jPanel3.setBackground(new java.awt.Color(41, 171, 226));

        btnCancellation.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCancellation.setText("Cancellation");
        btnCancellation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancellationMouseClicked(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        btnFlights.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnFlights.setText("Flights");
        btnFlights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFlightsMouseClicked(evt);
            }
        });
        btnFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightsActionPerformed(evt);
            }
        });

        btnPassengers.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnPassengers.setText("Passengers");
        btnPassengers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPassengersMouseClicked(evt);
            }
        });

        btnTickets.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnTickets.setText("Tickets");
        btnTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTicketsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFlights, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPassengers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCancellation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnCancellation, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, 530));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Unica One", 1, 60)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("DELTA AIR");
        jPanel21.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 330, 110));

        jLabel34.setFont(new java.awt.Font("Unica One", 1, 60)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("TO");
        jPanel21.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 100, 110));

        jLabel7.setFont(new java.awt.Font("Unica One", 1, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Welcome");
        jPanel21.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 270, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logo22.png"))); // NOI18N
        jPanel21.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 210, 100));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/2.jpg"))); // NOI18N
        jPanel21.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 560));

        home.addTab("tab1", jPanel21);

        maintab.addTab("tab1", home);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnfDelete.setBackground(new java.awt.Color(255, 102, 51));
        btnfDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnfDelete.setText("Delete");
        jPanel5.add(btnfDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));
        jPanel5.add(flDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 120, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Flight Code");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 100, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Source");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 90, -1));

        flSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Khulna", "Syhlet", "Rajshahi", "Barishal", "Cumilla" }));
        jPanel5.add(flSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 120, -1));

        flDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Khulna", "Syhlet", "Rajshahi", "Barishal", "Cumilla" }));
        jPanel5.add(flDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 120, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Destination");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 120, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setText("Take of Time");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 120, -1));
        jPanel5.add(flCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 130, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("Number of Seats");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 130, -1));
        jPanel5.add(flSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 130, -1));

        btnfSave.setBackground(new java.awt.Color(51, 204, 255));
        btnfSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnfSave.setText("Save");
        btnfSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfSaveMouseClicked(evt);
            }
        });
        jPanel5.add(btnfSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 70, -1));

        btnfUpdate.setBackground(new java.awt.Color(255, 204, 51));
        btnfUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnfUpdate.setText("Update");
        jPanel5.add(btnfUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        btnfReset.setBackground(new java.awt.Color(0, 204, 255));
        btnfReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnfReset.setText("Reset");
        jPanel5.add(btnfReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 70, -1));

        tblFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblFlights);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 760, 170));

        jPanel6.setBackground(new java.awt.Color(51, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Flights");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/1.jpg"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 500));

        flights.addTab("tab1", jPanel5);

        maintab.addTab("tab2", flights);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setBackground(new java.awt.Color(51, 204, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        jPanel9.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 70, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 204, 51));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        jPanel9.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        btnReset.setBackground(new java.awt.Color(0, 204, 255));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        jPanel9.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 70, -1));

        btnDelete.setBackground(new java.awt.Color(255, 102, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        jPanel9.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));
        jPanel9.add(pPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 120, -1));

        pNatinality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangladesh", "India", "Nepal", "United Kingdom", "Denmark", "Norway" }));
        jPanel9.add(pNatinality, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 110, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Nationality");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 90, -1));
        jPanel9.add(pName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Name");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 60, -1));

        pGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel9.add(pGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Gender");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 60, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Passport No:");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Address");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));
        jPanel9.add(pAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 120, -1));
        jPanel9.add(pPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 120, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Phone");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        tblPassengers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPassengers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPassengersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPassengers);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 790, 190));

        jPanel10.setBackground(new java.awt.Color(51, 204, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Passengers");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 880, 510));

        passengers.addTab("tab1", jPanel9);

        maintab.addTab("tab3", passengers);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSaveTickt.setBackground(new java.awt.Color(51, 204, 255));
        btnSaveTickt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSaveTickt.setText("Save");
        btnSaveTickt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveTicktMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveTicktMouseEntered(evt);
            }
        });
        jPanel13.add(btnSaveTickt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 70, -1));

        btnUpdateTickt.setBackground(new java.awt.Color(255, 204, 51));
        btnUpdateTickt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateTickt.setText("Update");
        jPanel13.add(btnUpdateTickt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        btnResetTickt.setBackground(new java.awt.Color(0, 204, 255));
        btnResetTickt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetTickt.setText("Reset");
        jPanel13.add(btnResetTickt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 70, -1));

        btnDeleteTickt.setBackground(new java.awt.Color(255, 102, 51));
        btnDeleteTickt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteTickt.setText("Delete");
        jPanel13.add(btnDeleteTickt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Passenger ID");
        jPanel13.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, -1));

        PassIdTickt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PassIdTicktItemStateChanged(evt);
            }
        });
        jPanel13.add(PassIdTickt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));
        jPanel13.add(nameTickt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Name");
        jPanel13.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 90, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Flight Code");
        jPanel13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 100, -1));

        flightCodeTickt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel13.add(flightCodeTickt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 90, -1));
        jPanel13.add(genderTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 90, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Gender");
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Passport No:");
        jPanel13.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));
        jPanel13.add(passportTickt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 100, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setText("Amount");
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));
        jPanel13.add(amountTickt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 100, -1));
        jPanel13.add(nationalityTickt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 100, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Nationality");
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, -1));

        tblTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblTickets);

        jPanel13.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 760, 170));

        jPanel14.setBackground(new java.awt.Color(51, 204, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Tickets");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/1.jpg"))); // NOI18N
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 510));

        tickets.addTab("tab1", jPanel13);

        maintab.addTab("tab4", tickets);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel17.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 740, 170));

        jButton13.setBackground(new java.awt.Color(255, 51, 51));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setText("Cancel");
        jPanel17.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jButton14.setBackground(new java.awt.Color(51, 204, 255));
        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton14.setText("Reset");
        jPanel17.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 70, -1));

        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton15.setText("Back");
        jPanel17.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 70, -1));
        jPanel17.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 120, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Flight Code");
        jPanel17.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 80, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Flight Date");
        jPanel17.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("Ticket ID");
        jPanel17.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 90, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel17.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 110, -1));

        jPanel18.setBackground(new java.awt.Color(51, 204, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Cancellation");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/1.jpg"))); // NOI18N
        jPanel17.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 510));

        cancellation.addTab("tab1", jPanel17);

        maintab.addTab("tab5", cancellation);

        jPanel4.add(maintab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 870, 600));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 870, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFlightsActionPerformed

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        maintab.setSelectedIndex(0);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnFlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFlightsMouseClicked
        // TODO add your handling code here:
        maintab.setSelectedIndex(1);
    }//GEN-LAST:event_btnFlightsMouseClicked

    private void btnPassengersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPassengersMouseClicked
        // TODO add your handling code here:
        maintab.setSelectedIndex(2);

    }//GEN-LAST:event_btnPassengersMouseClicked

    private void btnTicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketsMouseClicked
        // TODO add your handling code here:
        maintab.setSelectedIndex(3);
//        getPassenger();
//        
    }//GEN-LAST:event_btnTicketsMouseClicked

    private void btnCancellationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancellationMouseClicked
        // TODO add your handling code here:
        maintab.setSelectedIndex(4);
    }//GEN-LAST:event_btnCancellationMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:

        sql = "INSERT INTO passengers_table(p_name, p_nationality, p_gender, p_passport, p_address, p_phone)value(?,?,?,?,?,?)";

        try {
            ps = con.getCon().prepareStatement(sql);
            ps.setString(1, pName.getText().trim());
            ps.setString(2, pNatinality.getSelectedItem().toString());
            ps.setString(3, pGender.getSelectedItem().toString());
            ps.setString(4, pPassport.getText().trim());
            ps.setString(5, pAddress.getText().trim());
            ps.setString(6, pPhone.getText().trim());

            ps.executeUpdate();
            ps.close();
            con.getCon().close();

            JOptionPane.showMessageDialog(rootPane, "Data saved");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Data not saved" + ex);
            Logger.getLogger(DeshBoard2.class.getName()).log(Level.SEVERE, null, ex);
        }
//        getAllPassengerData();
        
        getPassenger();
        
       
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
//   tableColumns ={"p_id", "p_name", "p_nationality", "p_gender", "p_passport", "p_address", "p_phone"};  

        String Idnumber = id;

        sql = "update passengers_table set p_name=?, p_nationality=?, p_gender=?, p_passport=?, p_address=?, p_phone=? where p_id=?";

        try {
            ps = con.getCon().prepareStatement(sql);
            ps.setString(1, pName.getText().trim());
            ps.setString(2, pNatinality.getSelectedItem().toString());
            ps.setString(3, pGender.getSelectedItem().toString());
            ps.setString(4, pPassport.getText().trim());
            ps.setString(5, pAddress.getText().trim());
            ps.setString(6, pPhone.getText().trim());
            ps.setInt(7, Integer.parseInt(Idnumber.trim()));

            ps.executeUpdate();
            ps.close();
            con.getCon().close();

            JOptionPane.showMessageDialog(rootPane, "Data Updated");
            getAllPassengerData();

            id = null;

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Data Not Saved" + ex);
            Logger.getLogger(DeshBoard2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateMouseClicked
    String id;
    private void tblPassengersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPassengersMouseClicked
        // TODO add your handling code here:

        int row = tblPassengers.getSelectedRow();

        id = tblPassengers.getModel().getValueAt(row, 0).toString();
        String name = tblPassengers.getModel().getValueAt(row, 1).toString();
        String nationality = tblPassengers.getModel().getValueAt(row, 2).toString();
        String gender = tblPassengers.getModel().getValueAt(row, 3).toString();
        String passport = tblPassengers.getModel().getValueAt(row, 4).toString();
        String address = tblPassengers.getModel().getValueAt(row, 5).toString();
        String phone = tblPassengers.getModel().getValueAt(row, 6).toString();

        pName.setText(name);
        pNatinality.setSelectedItem(nationality);
        pGender.setSelectedItem(gender);
        pPassport.setText(passport);
        pAddress.setText(address);
        pPhone.setText(phone);

    }//GEN-LAST:event_tblPassengersMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        String Idnum = id;
        sql = "delete from passengers_table where p_id=?";

        try {
            ps = con.getCon().prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(Idnum.trim()));

            ps.executeLargeUpdate();
            ps.close();
            con.getCon().close();

            JOptionPane.showMessageDialog(rootPane, "Data Deleted");
            reset();

            getAllPassengerData();

            id = null;

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Data not saved" + ex);
            Logger.getLogger(DeshBoard2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    //Strting flights module from here
    //get data from mysql table
    String[] flTableColumns = {"fl_code", "fl_source", "fl_destination", "fl_date", "fl_seats"};

    public void getAllFlightsData() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(flTableColumns);

        tblFlights.setModel(model);

        sql = "select * from flight_table";

        try {
            ps = con.getCon().prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                String code = rs.getString("fl_code");
                String source = rs.getString("fl_source");
                String destination = rs.getString("fl_destination");
                Date date = rs.getDate("fl_date");
                int seats = rs.getInt("fl_seats");

                model.addRow(new Object[]{code, source, destination, date, seats});
            }
            ps.close();
            con.getCon().close();

        } catch (SQLException ex) {
            Logger.getLogger(DeshBoard2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void btnfSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfSaveMouseClicked
        // TODO add your handling code here:
        sql = "INSERT INTO flight_table(fl_code, fl_source, fl_destination, fl_date, fl_seats)value(?,?,?,?,?)";

        try {
            ps = con.getCon().prepareStatement(sql);
            ps.setString(1, flCode.getText().trim());
            ps.setString(2, flSource.getSelectedItem().toString());
            ps.setString(3, flDestination.getSelectedItem().toString());
            ps.setDate(4, convertDateToSql(flDate.getDate()));
            ps.setInt(5, Integer.parseInt(flSeats.getText().trim()));

            ps.executeUpdate();
            ps.close();
            con.getCon().close();

            JOptionPane.showMessageDialog(rootPane, "Data Saved");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Data Not Saved" + ex);
            Logger.getLogger(DeshBoard2.class.getName()).log(Level.SEVERE, null, ex);
        }
        getAllFlightsData();

    }//GEN-LAST:event_btnfSaveMouseClicked

    ///// Start tickets module from here///////////
    public void getPassenger() {
        

        sql = "SELECT * FROM passengers_table";
        try {
            ps = con.getCon().prepareStatement(sql);
            
            ResultSet rs1 = ps.executeQuery();

            while (rs1.next()) {
                
                int p_id = rs1.getInt("p_id");
                PassIdTickt.addItem(String.valueOf(p_id));
                System.out.println(p_id);

            }
            
            ps.close();
            con.getCon().close();
            rs1.close();

        } catch (SQLException ex) {
            Logger.getLogger(DeshBoard2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    public void getPassengerData() {
//        nameTickt.setText(null);

        sql = "select p_name from passengers_table where p_id =?";

        try {
            ps = con.getCon().prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(PassIdTickt.getSelectedItem().toString()));
            rs = ps.executeQuery();

            while (rs.next()) {
                nameTickt.setText(rs.getString("p_name"));
            }

            ps.close();
            rs.close();
            con.getCon().close();

        } catch (SQLException ex) {
            Logger.getLogger(DeshBoard2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void btnSaveTicktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveTicktMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSaveTicktMouseClicked

    private void btnSaveTicktMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveTicktMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveTicktMouseEntered

    private void PassIdTicktItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PassIdTicktItemStateChanged
        // TODO add your handling code here:

        getPassengerData();
    }//GEN-LAST:event_PassIdTicktItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeshBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeshBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeshBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeshBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeshBoard2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PassIdTickt;
    private javax.swing.JTextField amountTickt;
    private javax.swing.JButton btnCancellation;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteTickt;
    private javax.swing.JButton btnFlights;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPassengers;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResetTickt;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveTickt;
    private javax.swing.JButton btnTickets;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateTickt;
    private javax.swing.JButton btnfDelete;
    private javax.swing.JButton btnfReset;
    private javax.swing.JButton btnfSave;
    private javax.swing.JButton btnfUpdate;
    private javax.swing.JTabbedPane cancellation;
    private javax.swing.JTextField flCode;
    private com.toedter.calendar.JDateChooser flDate;
    private javax.swing.JComboBox<String> flDestination;
    private javax.swing.JTextField flSeats;
    private javax.swing.JComboBox<String> flSource;
    private javax.swing.JComboBox<String> flightCodeTickt;
    private javax.swing.JTabbedPane flights;
    private javax.swing.JTextField genderTicket;
    private javax.swing.JTabbedPane home;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JComboBox<String> jComboBox7;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTabbedPane maintab;
    private javax.swing.JTextField nameTickt;
    private javax.swing.JTextField nationalityTickt;
    private javax.swing.JTextField pAddress;
    private javax.swing.JComboBox<String> pGender;
    private javax.swing.JTextField pName;
    private javax.swing.JComboBox<String> pNatinality;
    private javax.swing.JTextField pPassport;
    private javax.swing.JTextField pPhone;
    private javax.swing.JTabbedPane passengers;
    private javax.swing.JTextField passportTickt;
    private javax.swing.JTable tblFlights;
    private javax.swing.JTable tblPassengers;
    private javax.swing.JTable tblTickets;
    private javax.swing.JTabbedPane tickets;
    // End of variables declaration//GEN-END:variables
}
