package model;
// Generated 11-Nov-2023 10:38:03 by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int id;
     private String giveName;
     private String lastName;
     private String gender;
     private String subject;

    public Student() {
    }

	
    public Student(int id) {
        this.id = id;
    }
    public Student(int id, String giveName, String lastName, String gender, String subject) {
       this.id = id;
       this.giveName = giveName;
       this.lastName = lastName;
       this.gender = gender;
       this.subject = subject;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getGiveName() {
        return this.giveName;
    }
    
    public void setGiveName(String giveName) {
        this.giveName = giveName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }




}


