/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.DbCon;

/**
 *
 * @author mm
 */
public class PrintTicket extends javax.swing.JFrame {

    /**
     * Creates new form PrintTicket
     */
    public PrintTicket() {
        initComponents();
    }

    PreparedStatement ps;
    String sql = "";
    ResultSet rs;

    DbCon con = new DbCon();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        printDemo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameTI = new javax.swing.JLabel();
        dateT = new javax.swing.JLabel();
        classT = new javax.swing.JLabel();
        sourceTI = new javax.swing.JLabel();
        destinationT = new javax.swing.JLabel();
        seatT = new javax.swing.JLabel();
        timeT = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nameT = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        sourceT = new javax.swing.JLabel();
        flightCodeT = new javax.swing.JLabel();
        destinationTI = new javax.swing.JLabel();
        seatTI = new javax.swing.JLabel();
        flightCodeTI = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        printDuplicate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 113, 188));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Print Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 230, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton2.setText("Show Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 160, 30));

        printDemo.setBackground(new java.awt.Color(255, 255, 255));
        printDemo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        printDemo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Time");
        printDemo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Destination");
        printDemo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        printDemo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 370));

        jPanel3.setBackground(new java.awt.Color(0, 113, 188));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Delta");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("BOARDING PASS");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 255));
        jLabel19.setText("AirLines");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Enjoy your trip");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
        );

        printDemo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Date:");
        printDemo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 100, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Passenger Name:");
        printDemo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 230, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Source");
        printDemo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Seat");
        printDemo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Flight Code");
        printDemo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Class");
        printDemo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        nameTI.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        nameTI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printDemo.add(nameTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 250, 60));

        dateT.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(dateT, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 170, 40));

        classT.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(classT, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 150, 40));

        sourceTI.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(sourceTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 150, 40));

        destinationT.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(destinationT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 150, 40));

        seatT.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(seatT, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 150, 40));

        timeT.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(timeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 150, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/barcoder.jpg"))); // NOI18N
        printDemo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, 290));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setText("Passenger Name:");
        printDemo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 160, 40));

        nameT.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(nameT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 210, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/barcode2.png"))); // NOI18N
        printDemo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 260, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel15.setText("Source");
        printDemo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setText("Flight Code");
        printDemo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setText("Destination");
        printDemo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setText("Seat");
        printDemo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, -1, -1));

        sourceT.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(sourceT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 150, 40));

        flightCodeT.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(flightCodeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 150, 40));

        destinationTI.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(destinationTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 160, 40));

        seatTI.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(seatTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 110, 40));

        flightCodeTI.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        printDemo.add(flightCodeTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 130, 40));

        jPanel1.add(printDemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 970, 370));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 80, 30));

        printDuplicate.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        printDuplicate.setText("Searche Tickets");
        printDuplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDuplicateActionPerformed(evt);
            }
        });
        jPanel1.add(printDuplicate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 140, 30));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 1080, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//         TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("print Data");

        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.60, 0.60);
                printDemo.print(g2);
                return Printable.PAGE_EXISTS;
            }

        });

        boolean ok = job.printDialog();
        if (ok) {

            try {
                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
        this.dispose();







        
        // Create a timestamp-based file name
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmss");
//        String fileName = "printData_" + sdf.format(new Date()) + ".pdf";
//
//        PrinterJob job = PrinterJob.getPrinterJob();
//        job.setJobName(fileName);
//
////        PrinterJob job = PrinterJob.getPrinterJob();
////        job.setJobName("print Data");
//        
//
//        job.setPrintable(new Printable() {
//            public int print(Graphics pg, PageFormat pf, int pageNum) {
//                pf.setOrientation(PageFormat.LANDSCAPE);
//                if (pageNum > 0) {
//                    return Printable.NO_SUCH_PAGE;
//                }
//                Graphics2D g2 = (Graphics2D) pg;
//                g2.translate(pf.getImageableX(), pf.getImageableY());
//                g2.scale(0.60, 0.60);
//                printDemo.print(g2);
//                return Printable.PAGE_EXISTS;
//            }
//
//        });
//
//        boolean ok = job.printDialog();
//        if (ok) {
//
//            try {
//                job.print();
//            } catch (PrinterException ex) {
//                ex.printStackTrace();
//            }
//        }
//        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        sql = "SELECT * from ticket_table";

        try {
            ps = con.getCon().prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                String name = rs.getString("p_name");
                String flightCode = rs.getString("fl_code");
                String source = rs.getString("source");
                String destination = rs.getString("destination");
                String date = rs.getString("date");
                String fClass = rs.getString("class");
                String time = rs.getString("time");
                String seat = rs.getString("seat");

                nameT.setText(name);
                nameTI.setText(name);
                flightCodeT.setText(flightCode);               
                flightCodeTI.setText(flightCode);               
                sourceT.setText(source);
                sourceTI.setText(source);
                destinationT.setText(destination);
                destinationTI.setText(destination);
                dateT.setText(date);
                
                classT.setText(fClass);
                timeT.setText(time);
                seatT.setText(seat);
                seatTI.setText(seat);
            }

        } catch (SQLException ex) {
            Logger.getLogger(PrintTicket.class.getName()).log(Level.SEVERE, null, ex);
        }



 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void printDuplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDuplicateActionPerformed
        // TODO add your handling code here:
        sql = "SELECT * from ticket_table where ticket_id=?";

        try {
            ps = con.getCon().prepareStatement(sql);
            int ticket = Integer.parseInt(txtId.getText());
            ps.setInt(1, ticket);

            rs = ps.executeQuery();

            while (rs.next()) {
                String name = rs.getString("p_name");
                String flightCode = rs.getString("fl_code");
                String source = rs.getString("source");
                String destination = rs.getString("destination");
                String date = rs.getString("date");
                String fClass = rs.getString("class");
                String time = rs.getString("time");
                String seat = rs.getString("seat");

                
                
                nameT.setText(name);
                nameTI.setText(name);
                flightCodeT.setText(flightCode);               
                flightCodeTI.setText(flightCode);               
                sourceT.setText(source);
                sourceTI.setText(source);
                destinationT.setText(destination);
                destinationTI.setText(destination);
                dateT.setText(date);
                
                classT.setText(fClass);
                timeT.setText(time);
                seatT.setText(seat);
                seatTI.setText(seat);
                
                
                
                
//                nameT.setText(name);
//                nameTI.setText( name);
//                classT.setText(flightCode);
//                classT.setText(source);
//                classT.setText(destination);
//                dateT.setText(date);
//                classT.setText(fClass);
//                classT.setText(time);
//                seatT.setText(seat);
            }

        } catch (SQLException ex) {
            Logger.getLogger(PrintTicket.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_printDuplicateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel classT;
    private javax.swing.JLabel dateT;
    private javax.swing.JLabel destinationT;
    private javax.swing.JLabel destinationTI;
    private javax.swing.JLabel flightCodeT;
    private javax.swing.JLabel flightCodeTI;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameT;
    private javax.swing.JLabel nameTI;
    private javax.swing.JPanel printDemo;
    private javax.swing.JButton printDuplicate;
    private javax.swing.JLabel seatT;
    private javax.swing.JLabel seatTI;
    private javax.swing.JLabel sourceT;
    private javax.swing.JLabel sourceTI;
    private javax.swing.JLabel timeT;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
